# Snyk
# Análisis básico de un contenedor con la herramienta de Snyk
# 

trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '5db8edef-185a-4e82-b89c-3f0d6dd38c1f'
  imageRepository: 'malevarrokart'
  containerRegistryn: 'myacr20079.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'
  sariflog: 'CodeAnalysisLogs'

pool:
  vmImage: $(vmImageName)

stages:
  - stage: SecurityScan
    displayName: SecurityAnalysis
    jobs:
      - job: Snyk
        displayName: Snyk
        pool:
          vmImage: $(vmImageName)
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'myacr20079'
            command: 'login'
        - task: SnykSecurityScan@1
          inputs:
            serviceConnectionEndpoint: 'SNYK2'
            testType: 'container'
            dockerImageName: '$(containerRegistryn)/$(imageRepository)'
            dockerfilePath: '$(dockerfilePath)'
            monitorWhen: 'always'
            failOnIssues: false